// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID          uuid.UUID
	Author      string
	Date        pgtype.Timestamp
	Createdat   pgtype.Timestamp
	Updatedat   pgtype.Timestamp
	Title       string
	Description string
	Genre       string
	Numberpages int32
}
