// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID              pgtype.UUID
	Author          string
	Date            pgtype.Timestamp
	Createdat       pgtype.Timestamp
	Updatedat       pgtype.Timestamp
	Title           string
	Description     string
	Genre           string
	Numberpages     int32
	Price           pgtype.Numeric
	Quantityonstock int32
}
