// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const addBook = `-- name: AddBook :one
INSERT INTO books (
    title, description,
    genre, author,
    numberPages
) VALUES (
    $1, $2,
    $3, $4,
    $5
)
RETURNING id
`

type AddBookParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Genre       string `json:"genre"`
	Author      string `json:"author"`
	Numberpages int32  `json:"numberpages"`
}

func (q *Queries) AddBook(ctx context.Context, arg AddBookParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, addBook,
		arg.Title,
		arg.Description,
		arg.Genre,
		arg.Author,
		arg.Numberpages,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const allBooks = `-- name: AllBooks :many
SELECT id, author, createdat, updatedat, title, description, genre, numberpages FROM books
`

func (q *Queries) AllBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, allBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Createdat,
			&i.Updatedat,
			&i.Title,
			&i.Description,
			&i.Genre,
			&i.Numberpages,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteBook = `-- name: DeleteBook :one
DELETE FROM books
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteBook(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteBook, id)
	err := row.Scan(&id)
	return id, err
}

const getBook = `-- name: GetBook :one
SELECT id, author, createdat, updatedat, title, description, genre, numberpages FROM books
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBook(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Createdat,
		&i.Updatedat,
		&i.Title,
		&i.Description,
		&i.Genre,
		&i.Numberpages,
	)
	return i, err
}
