environment: "prod" # may be "local" or "prod"

http_server:
  port: 8080
  address: "127.0.0.1"
  timeout: 6s # write and read timeouts
  idle_timeout: 60s

metric_server:
  port: 8081
  address: "127.0.0.1"

database:
  engine: "postgres"
  host: "127.0.0.1"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "postgres"
  migration_dir: "./sql/migrations"
