CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE books (
    id UUID DEFAULT uuid_generate_v4 () PRIMARY KEY,
    author VARCHAR(256) NOT NULL,
    date TIMESTAMP NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    title VARCHAR(256) NOT NULL,
    description VARCHAR NOT NULL,
    genre VARCHAR(256) NOT NULL,
    numberPages INTEGER NOT NULL,
    price NUMERIC(10, 2) NULL,
    quantityOnStock INTEGER NOT NULL
)
